# Generated by Django 3.0.3 on 2020-03-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='data_inicio',
        ),
    ]
